### ISSUE TITLE
RSS Feed example broken

### ISSUE THREAD

**Issue by acdavidh** [SuperOffice/SDK-Doc#4]
Hello,

The RSS Feed example hasn't survived the markdown conversion, see: https://community.superoffice.com/documentation/SDK/SO.NetServer.Data.Access/html/Examples-Demos-RSSFeedGenerationinVB-net-GeneratetheXMLContentswiththeRelevantActivityInformation.htm

@xt1

**Comment by AnthonyYates** [comment]
This issue has been fixed and will be included in the next published release - Aug 20th, 2020.
